package org.hibernate.community.dialect.test;

import jakarta.persistence.Table;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Column;
import jakarta.persistence.Lob;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Date;

/**
 * Contact entity for FileMaker database.
 * Field types are aligned with FileMaker JDBC driver capabilities:
 * - Strings map to VARCHAR
 * - Numbers map to DOUBLE
 * - Dates map to TIMESTAMP
 * - Large text fields map to VARCHAR/TEXT
 * - Binary data maps to BLOB
 * 
 * ID Generation:
 * - Primary key (id) is handled by FileMaker as a serial integer
 * - UUID field is also generated by FileMaker as an alternative unique identifier
 * Both are generated on record creation by the database, not by Hibernate
 * 
 * Advanced Features:
 * - Large text fields (notes) for testing text handling
 * - Binary data (photo) for BLOB handling
 * - Date/time fields with timezone support
 * - System columns (ROWID, ROWMODID) for versioning
 */
@Entity
@Table(name = "contact")
public class Contact implements Serializable {
    private static final long serialVersionUID = 1L;
    
    // ID is generated by FileMaker as a serial integer
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(insertable = false, updatable = false)
    private Long id;

    // Required fields
    @Column(nullable = false)
    private String email;
    
    @Column(nullable = false)
    private String login;
    
    @Column(nullable = false)
    private String password;

    // Basic fields
    @Column(name = "first_name")
    private String firstName;
    
    @Column(name = "last_name")
    private String lastName;
    
    private String title;
    
    @Column(name = "job_title")
    private String jobTitle;

    private String company;
    
    private String website;
    
    // Large text fields for testing
    @Column(length = 100000)
    private String notes;

    @Column(name = "photo_url")
    private String photoUrl;

    @Column(name = "photo_content_type")
    private String photoContentType;
    
    // Date/time fields with timezone
    @Column(name = "last_contact_date")
    @Temporal(TemporalType.TIMESTAMP)
    private Date lastContactDate;
    
    // System columns from FileMaker
    @Column(name = "ROWID", insertable = false, updatable = false)
    private Long recordId;
    
    @Column(name = "ROWMODID", insertable = false, updatable = false)
    private Integer modificationCount;
    
    // Generated fields
    @Column(insertable = false, updatable = false)
    private String uuid;
    
    @Column(insertable = false, updatable = false)
    private String sku;

    @Column(name = "create_timestamp", insertable = false, updatable = false)
    private LocalDateTime createTimestamp;
    
    @Column(name = "update_timestamp", insertable = false, updatable = false)
    private LocalDateTime updateTimestamp;

    public Contact() {
    }

    public Contact(String email, String login, String password) {
        this.email = email;
        this.login = login;
        this.password = password;
    }

    // Getters and setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getPhotoUrl() {
        return photoUrl;
    }

    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl;
    }

    public String getJobTitle() {
        return jobTitle;
    }

    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getWebsite() {
        return website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public String getPhotoContentType() {
        return photoContentType;
    }

    public void setPhotoContentType(String photoContentType) {
        this.photoContentType = photoContentType;
    }

    public Date getLastContactDate() {
        return lastContactDate;
    }

    public void setLastContactDate(Date lastContactDate) {
        this.lastContactDate = lastContactDate;
    }

    public Long getRecordId() {
        return recordId;
    }

    public void setRecordId(Long recordId) {
        this.recordId = recordId;
    }

    public Integer getModificationCount() {
        return modificationCount;
    }

    public void setModificationCount(Integer modificationCount) {
        this.modificationCount = modificationCount;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku;
    }

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public LocalDateTime getCreateTimestamp() {
        return createTimestamp;
    }

    public void setCreateTimestamp(LocalDateTime createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    public LocalDateTime getUpdateTimestamp() {
        return updateTimestamp;
    }

    public void setUpdateTimestamp(LocalDateTime updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }
}
