package org.hibernate.community.dialect.test;

import static org.junit.jupiter.api.Assertions.*;

import java.time.LocalDateTime;
import java.util.List;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.query.Query;
import org.junit.jupiter.api.*;

import io.qameta.allure.*;

/**
 * Integration Tests for FileMaker Dialect
 * 
 * included TESTS:
 * 1. testBasicContactCreation - Basic CRUD operations with required fields
 * 2. testCreateContactWithGeneratedFields - Verifies database-generated fields
 * 3. testModificationCounter - Verifies MODID behavior
 * 4. testUuidAndSkuPersistence - Verifies UUID and SKU generation
 * 5. testUpdateContact - Verifies contact updates and system columns
 * 6. testDeleteContact - Verifies contact deletion
 * 7. testAdvancedQueries - Verifies HQL query functionality
 * 8. testTransactionRollback - Verifies transaction management
 * 9. testBatchOperations - Verifies batch operations
 */
@Epic("FileMaker Hibernate Integration")
@Feature("Core CRUD Operations")
@Owner("FileMaker Team")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
@DisplayName("FileMaker Dialect Integration Tests")
public class IntegrationTest {
    
    private static SessionFactory sessionFactory;
    private Session session;
    private Transaction transaction;
    
    @BeforeAll
    static void setupClass() {
        sessionFactory = HibernateUtil.getSessionFactory();
    }
    
    @AfterAll
    static void tearDownClass() {
        if (sessionFactory != null) {
            sessionFactory.close();
        }
    }
    
    @BeforeEach
    void setUp() {
        session = sessionFactory.openSession();
        transaction = session.beginTransaction();
    }
    
    @AfterEach
    void tearDown() {
        if (transaction != null && transaction.isActive()) {
            transaction.rollback();
        }
        if (session != null && session.isOpen()) {
            session.close();
        }
    }
    
    @Test
    @Order(0)
    @Story("Basic Entity Creation")
    @Description("Test basic entity creation with a Contact entity")
    @Severity(SeverityLevel.BLOCKER)
    @DisplayName("Test Basic Entity Creation")
    void testBasicEntityCreation() {
        Contact contact = new Contact("test@example.com", "jdoe", "password123");
        contact.setFirstName("John");
        contact.setLastName("Doe");
        
        // Save the contact
        session.persist(contact);
        transaction.commit();
        
        // Get the ID from the persisted entity
        Long savedId = contact.getId();
        assertNotNull(savedId, "ID should be generated by database");
        assertTrue(savedId > 0, "Generated ID should be positive");
        
        // Clear session and load fresh to verify persistence
        session.clear();
        Contact savedContact = session.get(Contact.class, savedId);
        System.out.println("Reloaded contact - ID: " + savedContact.getId());
        
        assertNotNull(savedContact, "Contact should be saved");
        assertEquals("John", savedContact.getFirstName());
        assertEquals("Doe", savedContact.getLastName());
        assertEquals("test@example.com", savedContact.getEmail());
    }

    @Test
    @Order(1)
    @Story("Generated Fields")
    @Description("Verify that FileMaker correctly handles auto-generated fields like UUID, SKU, and timestamps")
    @Severity(SeverityLevel.CRITICAL)
    @DisplayName("Test Entity Creation with Generated Fields")
    void testCreateEntityWithGeneratedFields() {
        Contact contact = new Contact("test@example.com", "testuser", "test123");
        contact.setTitle("Mr.");
        contact.setJobTitle("Senior Developer");
        contact.setCompany("Example Corp");
        
        session.persist(contact);
        transaction.commit();
        session.clear();
        
        Contact savedContact = session.get(Contact.class, contact.getId());
        assertNotNull(savedContact.getUuid(), "UUID should be generated");
        assertNotNull(savedContact.getSku(), "SKU should be generated");
        assertNotNull(savedContact.getCreateTimestamp(), "Create timestamp should be set");
        assertNotNull(savedContact.getUpdateTimestamp(), "Update timestamp should be set");
        assertEquals(0, savedContact.getModificationCount(), "Initial modification count should be 0");
        assertEquals("Mr.", savedContact.getTitle(), "Title should be saved correctly");
        assertEquals("Senior Developer", savedContact.getJobTitle(), "Job title should be saved correctly");
        assertEquals("Example Corp", savedContact.getCompany(), "Company should be saved correctly");
        assertEquals("test@example.com", savedContact.getEmail(), "Email should be saved correctly");
        assertEquals("testuser", savedContact.getLogin(), "Login should be saved correctly");
        
        LocalDateTime initialUpdateTimestamp = savedContact.getUpdateTimestamp();
        LocalDateTime initialCreateTimestamp = savedContact.getCreateTimestamp();
        
        // Add a small delay to ensure FileMaker updates the timestamp
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
        
        // Test update timestamp changes
        transaction = session.beginTransaction();
        savedContact.setTitle("Dr.");
        savedContact.setEmail("updated@example.com");
        session.merge(savedContact);
        transaction.commit();
        session.clear();
        
        Contact updatedContact = session.get(Contact.class, contact.getId());
        assertEquals("Dr.", updatedContact.getTitle(), "Title should be updated");
        assertEquals("updated@example.com", updatedContact.getEmail(), "Email should be updated");
        assertTrue(updatedContact.getUpdateTimestamp().isAfter(initialUpdateTimestamp),
                  "Update timestamp should be later after modification");
        assertEquals(initialCreateTimestamp, updatedContact.getCreateTimestamp(),
                    "Create timestamp should remain unchanged");
        assertTrue(updatedContact.getModificationCount() > 0, 
                  "Modification count should increase after update");
    }

    @Test
    @Order(2)
    @Story("Modification Counter")
    @Description("Verify that FileMaker correctly handles the modification counter (ROWMODID)")
    @Severity(SeverityLevel.CRITICAL)
    @DisplayName("Test FileMaker Record Modification Counter (ROWMODID)")
    void testModificationCounter() {
        // Create initial contact with required fields
        Contact contact = new Contact("test.user@example.com", "tuser", "test123");
        
        session.persist(contact);
        transaction.commit();
        session.clear();
        
        // Get initial ROWMODID - should be 0 for new records
        Contact savedContact = session.get(Contact.class, contact.getId());
        Integer initialModCount = savedContact.getModificationCount();
        assertNotNull(initialModCount, "ROWMODID should be set by FileMaker");
        assertEquals(0, initialModCount, "Initial ROWMODID should be 0");
        
        // Store the ROWID for later comparison
        Long recordId = savedContact.getRecordId();
        assertNotNull(recordId, "ROWID should be set by FileMaker");
        
        // Start new transaction for modification
        transaction = session.beginTransaction();
        
        // Modify contact
        savedContact.setEmail("test.updated@example.com");
        session.merge(savedContact);
        transaction.commit();
        session.clear();
        
        // Get fresh copy from database
        Contact updatedContact = session.get(Contact.class, contact.getId());
        
        // Verify ROWMODID was incremented by FileMaker
        assertNotNull(updatedContact.getModificationCount(), "ROWMODID should still be set");
        assertTrue(updatedContact.getModificationCount() > initialModCount, 
            String.format("ROWMODID should be incremented by FileMaker after modification (was: %d, now: %d)", 
                initialModCount, updatedContact.getModificationCount()));
        
        // Verify ROWID remains unchanged
        assertEquals(recordId, updatedContact.getRecordId(),
            "ROWID should never change after record creation");
    }

    @Test
    @Order(3)
    @Story("Autoentered Value Persistence")
    @Description("Verify that FileMaker correctly handles autoentered values like UUID and SKU")
    @Severity(SeverityLevel.NORMAL)
    @DisplayName("Test Autoentered value Persistence")
    void testAutoenterValuePersistence() {
        Contact contact = new Contact("test.user@example.com", "tuser", "test123");
        
        session.persist(contact);
        transaction.commit();
        session.clear();
        
        Contact savedContact = session.get(Contact.class, contact.getId());
        String initialUuid = savedContact.getUuid();
        String initialSku = savedContact.getSku();
        
        assertNotNull(initialUuid, "UUID should be set");
        assertNotNull(initialSku, "SKU should be set");
        
        transaction = session.beginTransaction();
        savedContact.setEmail("updated@example.com");
        session.merge(savedContact);
        transaction.commit();
        session.clear();
        
        Contact updatedContact = session.get(Contact.class, contact.getId());
        assertEquals(initialUuid, updatedContact.getUuid(),
            "UUID should remain unchanged after modification");
        assertEquals(initialSku, updatedContact.getSku(),
            "SKU should remain unchanged after modification");
    }

    @Test
    //@Disabled("Field validation error - required fields not set")
    @Order(4)
    @Story("ROWID Persistence")
    @Description("Verify that FileMaker correctly handles the ROWID")
    @Severity(SeverityLevel.NORMAL)
    @DisplayName("Test ROWID Persistence")
    void testRowIdPersistence() {
        // Create initial contact
        Contact contact = new Contact("test.user@example.com", "tuser", "test123");
        
        session.persist(contact);
        transaction.commit();
        session.clear();
        
        // Get initial row_id
        Contact savedContact = session.get(Contact.class, contact.getId());
        Long initialRowId = savedContact.getRecordId();
        assertNotNull(initialRowId, "Row ID should be set");
        
        // Modify contact
        transaction = session.beginTransaction();
        savedContact.setEmail("test.updated@example.com");
        session.merge(savedContact);
        transaction.commit();
        session.clear();
        
        // Verify row_id remains unchanged
        Contact updatedContact = session.get(Contact.class, contact.getId());
        assertEquals(initialRowId, updatedContact.getRecordId(),
            "row_id should remain unchanged after modification");
    }

    @Test
    @Order(5)
    @Story("Entity Update")
    @Description("Verify that FileMaker correctly handles entity updates")
    @Severity(SeverityLevel.CRITICAL)
    @DisplayName("Test Entity Update")
    void testUpdateEntity() {
        // Create a contact with all required fields
        Contact contact = new Contact("bob@example.com", "bsmith", "test123");
        contact.setFirstName("Bob");
        contact.setLastName("Smith");
        
        session.persist(contact);
        transaction.commit();
        session.clear();
        
        // Get the saved contact
        Contact savedContact = session.get(Contact.class, contact.getId());
        assertNotNull(savedContact, "Contact should be saved");
        assertEquals("bob@example.com", savedContact.getEmail());
        
        // Store initial ROWMODID and ROWID for comparison
        Integer initialModCount = savedContact.getModificationCount();
        Long recordId = savedContact.getRecordId();
        
        // Update the contact
        transaction = session.beginTransaction();
        savedContact.setEmail("bob.smith@example.com");
        savedContact.setCompany("Example Corp");
        savedContact.setJobTitle("Senior Developer");
        session.merge(savedContact);
        transaction.commit();
        session.clear();
        
        // Verify updates
        Contact updatedContact = session.get(Contact.class, contact.getId());
        assertNotNull(updatedContact, "Contact should still exist");
        assertEquals("bob.smith@example.com", updatedContact.getEmail());
        assertEquals("Example Corp", updatedContact.getCompany());
        assertEquals("Senior Developer", updatedContact.getJobTitle());
        
        // Verify FileMaker system columns
        assertTrue(updatedContact.getModificationCount() > initialModCount,
            "ROWMODID should be incremented after update");
        assertEquals(recordId, updatedContact.getRecordId(),
            "ROWID should remain unchanged");
    }
    
    @Test
    @Order(6)
    @Story("Entity Deletion")
    @Description("Verify that FileMaker correctly handles entity deletion")
    @Severity(SeverityLevel.CRITICAL)
    @DisplayName("Test Entity Deletion")
    void testDeleteEntity() {
        // Create a contact
        Contact contact = new Contact("alice@example.com", "abrown", "pass456");
        
        session.persist(contact);
        transaction.commit();
        
        Long contactId = contact.getId();
        
        // Start new transaction
        transaction = session.beginTransaction();
        
        // Delete contact
        session.remove(contact);
        transaction.commit();
        
        // Try to retrieve deleted contact
        Contact deletedContact = session.get(Contact.class, contactId);
        assertNull(deletedContact, "Contact should be null after deletion");
    }
    
    @Test
    @Order(7)
    @Story("Advanced Queries")
    @Description("Verify that FileMaker correctly handles advanced queries")
    @Severity(SeverityLevel.NORMAL)
    @DisplayName("Test Advanced Query Features")
    void testAdvancedQueries() {
        // Create contacts with various fields
        createTestContacts();
        transaction.commit();
        session.clear(); // Clear session to ensure fresh data retrieval
        
        // Test query by company
        Query<Contact> companyQuery = session.createQuery(
            "FROM Contact c WHERE c.company = :company", Contact.class);
        companyQuery.setParameter("company", "Example Corp");
        List<Contact> companyContacts = companyQuery.getResultList();
        assertFalse(companyContacts.isEmpty(), "Should find contacts by company");
        assertTrue(companyContacts.stream().allMatch(c -> "Example Corp".equals(c.getCompany())),
            "All contacts should be from Example Corp");
        
        // Test query by job title
        Query<Contact> jobQuery = session.createQuery(
            "FROM Contact c WHERE c.jobTitle LIKE :pattern", Contact.class);
        jobQuery.setParameter("pattern", "%Developer%");
        List<Contact> developerContacts = jobQuery.getResultList();
        assertFalse(developerContacts.isEmpty(), "Should find contacts by job title");
        assertTrue(developerContacts.stream().allMatch(c -> c.getJobTitle().contains("Developer")),
            "All contacts should have Developer in their title");
        
        // Test complex query with multiple conditions
        Query<Contact> complexQuery = session.createQuery(
            "FROM Contact c WHERE c.company = :company " +
            "AND c.jobTitle LIKE :jobPattern " +
            "AND c.email LIKE :emailPattern", Contact.class);
        complexQuery.setParameter("company", "Example Corp");
        complexQuery.setParameter("jobPattern", "%Developer%");
        complexQuery.setParameter("emailPattern", "%.com");
        
        List<Contact> complexResults = complexQuery.getResultList();
        assertFalse(complexResults.isEmpty(), "Should find contacts with complex query");
        
        // Clean up test data
        transaction = session.beginTransaction();
        for (Contact c : complexResults) {
            session.remove(c);
        }
        transaction.commit();
    }
    
    private void createTestContacts() {
        String[] companies = {"Example Corp", "Test Inc", "Dev LLC"};
        String[] jobTitles = {"Senior Developer", "Project Manager", "QA Engineer"};
        
        for (int i = 0; i < companies.length; i++) {
            Contact contact = new Contact("test" + i + "@example.com", "tuser" + i, "test123");
            // Test-specific fields
            contact.setFirstName("Test");
            contact.setLastName("User" + i);
            contact.setCompany(companies[i]);
            contact.setJobTitle(jobTitles[i]);
            
            session.persist(contact);
        }
    }
    
    @Test
    @Order(8)
    @Story("Transaction Management")
    @Description("Verify that transactions are properly managed and can be rolled back")
    @Severity(SeverityLevel.CRITICAL)
    @DisplayName("Test Transaction Rollback")
    void testTransactionRollback() {
        // Create a contact with all required fields
        Contact contact = new Contact("test@example.com", "tuser", "testpass");
        contact.setFirstName("Test");
        contact.setLastName("User");
        
        session.persist(contact);
        transaction.commit();
        session.clear();
        
        Long contactId = contact.getId();
        
        // Get initial state
        Contact savedContact = session.get(Contact.class, contactId);
        String initialEmail = savedContact.getEmail();
        Integer initialModCount = savedContact.getModificationCount();
        
        // Start new transaction
        transaction = session.beginTransaction();
        
        // Update contact
        savedContact.setEmail("invalid@example.com");
        session.merge(savedContact);
        
        // Rollback transaction
        transaction.rollback();
        session.clear();
        
        // Verify the email wasn't updated
        Contact unchangedContact = session.get(Contact.class, contactId);
        assertEquals(initialEmail, unchangedContact.getEmail(),
            "Email should remain unchanged after rollback");
        assertEquals(initialModCount, unchangedContact.getModificationCount(),
            "Modification count should remain unchanged after rollback");
        
        // Clean up
        transaction = session.beginTransaction();
        session.remove(unchangedContact);
        transaction.commit();
    }
    
    @Test
    @Order(9)
    @Story("Batch Operations")
    @Description("Verify that batch operations are properly handled")
    @Severity(SeverityLevel.NORMAL)
    @DisplayName("Test Batch Operations")
    void testBatchOperations() {
        // Create multiple contacts in batch
        for (int i = 1; i <= 5; i++) {
            Contact contact = new Contact("batch" + i + "@example.com", "buser" + i, "batch123");
            // Additional fields
            contact.setFirstName("Batch");
            contact.setLastName("User " + i);
            contact.setCompany("Batch Corp");
            contact.setJobTitle("Batch Tester " + i);
            
            session.persist(contact);
            
            if (i % 3 == 0) { // Flush every 3 records
                session.flush();
                session.clear();
            }
        }
        
        transaction.commit();
        session.clear();
        
        // Query to verify batch insert
        Query<Long> countQuery = session.createQuery(
            "SELECT COUNT(c) FROM Contact c WHERE c.email LIKE :pattern",
            Long.class
        );
        countQuery.setParameter("pattern", "batch%");
        
        Long count = countQuery.getSingleResult();
        assertEquals(5L, count, "Should have inserted 5 batch contacts");
        
        // Clean up batch records
        transaction = session.beginTransaction();
        Query<?> deleteQuery = session.createQuery(
            "DELETE FROM Contact c WHERE c.email LIKE :pattern"
        );
        deleteQuery.setParameter("pattern", "batch%");
        deleteQuery.executeUpdate();
        transaction.commit();
    }
}